spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: lb://fraud
          predicates:
            - Path=/api/v1/fraud-check/**
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notification/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 9090

eureka:
  instance:
    hostname: api-gateway
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
