spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false

