spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

